### PR TITLE
Fix Send Fiat Amount

### LINKED ISSUE #480: [Send] Editing dollar amount doesn’t work
### What version are you using?

1.6.23 (31)

### What did you do?

Opened the Send amount and tried inputting a DOLLAR amount right away (you need to tap on the little “swap” button below the amount number to input a dollar amount).

I can’t always input the dollar amount.

### What did you expect to see?

The amount reflect what I am typing.

### What did you see instead?

Nothing happens.

Image

### PR DESCRIPTION
**Pull request by leofelix077**
Adjust templating of Fiat amount when switching from entering token amount
Closes #480 

https://github.com/user-attachments/assets/9feff34a-6e19-4246-a590-a53993796800

#### PR structure

- [x] This PR does not mix refactoring changes with feature changes (break it down into smaller PRs if not).
- [x] This PR has reasonably narrow scope (break it down into smaller PRs if not).
- [x] This PR includes relevant before and after screenshots/videos highlighting these changes.
- [x] I took the time to review my own PR.

#### Testing

- [x] These changes have been tested and confirmed to work as intended on Android.
- [x] These changes have been tested and confirmed to work as intended on iOS.
- [ ] ~These changes have been tested and confirmed to work as intended on small iOS screens.~
- [ ] ~These changes have been tested and confirmed to work as intended on small Android screens.~
- [x] I have tried to break these changes while extensively testing them.
- [x] This PR adds tests for the new functionality or fixes.

#### Release

- [ ] This is not a breaking change.
- [x] This PR updates existing JSDocs when applicable.
- [x] This PR adds JSDocs to new functionalities.
- [ ] I've checked with the product team if we should add metrics to these changes.
- [ ] I've shared relevant before and after screenshots/videos highlighting these changes with the design team and they've approved the changes.

### CODE REVIEW

File: src/hooks/useTokenFiatConverter.ts [hunk 1]
```diff
@@ -15,12 +16,14 @@ interface UseTokenFiatConverterProps {
...
-  fiatAmount: string;
+  fiatAmount: string; // Internal value (dot notation)
+  fiatAmountDisplay: string; // Display value (locale-formatted)
   showFiatAmount: boolean;
   setShowFiatAmount: (show: boolean) => void;
   handleDisplayAmountChange: (key: string) => void;
   setTokenAmount: (amount: string) => void;
   setFiatAmount: (amount: string) => void;
+  updateFiatDisplay: (amount: string) => void;
 }
```
Comment (aristidesstaffieri) [inline src/hooks/useTokenFiatConverter.ts]: one thing that sticks out to me about this hook is that it uses multiple related but separate state variables to trigger a cascade of effects in order to reach the correct state.

`tokenAmount → fiatAmount → fiatAmountDisplay`

This works but leaves a path them for them to fall out of sync. What about refactoring this into a `useReducer` workflow that can provide the state changes atomically?

I think if you really prefer the semantics of `useState` instead we could consider deriving the display values from the real amounts directly(memo value) instead of storing them in state. This would reduce the number of renders needed for this update.

**Comment by leofelix077** [comment]
@CassioMG just quick update: saw your comment, just will take a bit to get back to it due to the other https://github.com/stellar/freighter-mobile/issues/520 issue. but thanks a lot for the scenarios. will check them out and post videos of it as soon I can get to it

File: src/hooks/useTokenFiatConverter.ts (hunk 1 above)
Comment (leofelix077) [reply src/hooks/useTokenFiatConverter.ts]: To be fair I had forgotten about the useReducer/reducers in general. it went to the back of my mind, as we don't use it anywhere else in the code and I hadn't seen it in a while, but I think it's a much better approach for manipulating multiple values at once
