### PR TITLE
Handle Send to contracts

### LINKED ISSUE #188: Sending to a Contract not working on Mainnet
Sending to a Contract "C" address seems to work on Testnet but is not working on Mainnet.

On the amount screen nothing happens after you tap on the "Review" button (see video below).
It appears it doesn't matter if it's a SAC or a Custom Token, the same behavior applies.

To repro this you can try sending a payment to either address below on `Mainnet`:
- USDC `SAC` address: `CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75`
- USDL `Custom Token` address: `CB4PO24UJF7KFNUNQJISIRPO2KSULUWIOP4JT3S3KYW5UFXRQPZD34E4`

On Testnet you should be able to complete a payment on the C address below:
- USDC SAC address: CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA
- TEST `Custom Token` address: CB2GPQAQJAJIGBXVQBMZ4GXMV7QSTA4LQASUAJXCD4ZYUKH2C25HKFQR

https://github.com/user-attachments/assets/7a9e89f7-c144-4a03-a387-bd3b1dc139fd

### PR DESCRIPTION
**Pull request by danilosilvackl**
This PR fixes some issues we found out on the MVPv3:

## Work done:
- Improved transaction handling for contracts
  - now we use the backend to prepare the transaction before sending it
- Improved UI on the token lists for the Swap screen and bottom sheet
- Improved the numeric keyboard UI on smaller screens

### Now
|  |  |  |  |
| :---: | :---: | :---: | :---: |
| iPhone 16 pro (send) | iPhone 16 pro (swap) | iPhone SE (send) | iPhone SE (swap) |

|  |  |  |  |
| :---: | :---: | :---: | :---: |
| Pixel 9 (send) | Pixel 9 (swap) | Galaxy A3 (send) | Galaxy A3 (swap) |

## Contract transactions:

https://github.com/user-attachments/assets/e6a61f2c-08dd-4876-ba59-d65a292a8333

|  |
| :---: | 
| _Server was taking its sweet time with that transaction, so i stopped recording but here is the detail of that successful transaction_ |

## Swap token list

https://github.com/user-attachments/assets/fd5051f9-06f8-4a64-b24a-3b282e111380

closes #188

### CODE REVIEW

File: src/ducks/transactionBuilder.ts [hunk 1]
```diff
@@ -123,12 +141,15 @@ export const useTransactionBuilderStore = create<TransactionBuilderState>(
           );
         }
 
-        set({
-          transactionXDR: finalXdr,
-          isBuilding: false,
-          signedTransactionXDR: null,
-          transactionHash: null,
-        });
+        // Ignore if an even newer cycle started
```
Comment (CassioMG) [inline src/ducks/transactionBuilder.ts:144]: would you mind expanding a bit more on the description here? I think it's looking too succinct and a little confusing

File: src/ducks/transactionBuilder.ts [hunk 2]
```diff
@@ -194,11 +224,13 @@ export const useTransactionBuilderStore = create<TransactionBuilderState>(
           },
         );
 
-        set({
-          error: errorMessage,
-          isBuilding: false,
-          transactionXDR: null,
-        });
+        if (get().requestId === newRequestId) {
```
Comment (CassioMG) [inline src/ducks/transactionBuilder.ts:227]: add description

File: src/ducks/transactionBuilder.ts [hunk 3]
```diff
@@ -254,10 +288,14 @@ export const useTransactionBuilderStore = create<TransactionBuilderState>(
         });
 
         const { hash } = result;
-        set({
-          transactionHash: hash,
-          isSubmitting: false,
-        });
+
+        // Ignore if another submit started later
+        if (get().requestId === currentRequestId) {
```
Comment (CassioMG) [inline src/ducks/transactionBuilder.ts:293]: update description (it's ok if we need to repeat part or most of the other descriptions)

File: src/components/screens/SwapScreen/SwapScreen.tsx [hunk 4]
```diff
@@ -49,7 +49,7 @@ const SwapScreen: React.FC<SwapScreenProps> = ({ navigation }) => {
   };
 
   return (
-    <BaseLayout insets={{ top: false }}>
+    <BaseLayout insets={{ top: false, bottom: false }}>
```
Comment (CassioMG) [inline src/components/screens/SwapScreen/SwapScreen.tsx:52]: nit: since you are working on it, would you mind playing with adding a `ListFooterComponent={<View className="h-10" />}` on the `BalancesList` component and check if it looks good? Similar to what we are doing with the `HistoryList` component. I think adding this extra padding at the bottom of the list is nice because it makes 100% clear for the user that they've achieved the end of the list. Wdyt?

Comment (danilosilvackl) [reply src/components/screens/SwapScreen/SwapScreen.tsx:38]: just tried it, it does look great!

File: src/ducks/transactionBuilder.ts (hunk 1 above)
Comment (danilosilvackl) [reply src/ducks/transactionBuilder.ts]: I added more descriptive text on this comment, thanks for asking!

File: src/components/NumericKeyboard.tsx [hunk 5]
```diff
@@ -29,23 +29,23 @@ const NumericKeyboard: React.FC<NumericKeyboardProps> = ({ onPress }) => {
   );
 
   return (
-    <View className="gap-[12px]">
-      <View className="flex-row gap-[12px]">
+    <View className="gap-[12px] max-xs:gap-[4px]">
```
[the remark this answers is not in the document]
Comment (CassioMG) [reply src/components/NumericKeyboard.tsx:32]: nice, good job on figuring this out!

File: src/components/BottomSheet.tsx [hunk 6]
```diff
@@ -64,6 +65,7 @@ const BottomSheet: React.FC<BottomSheetProps> = ({
   enablePanDownToClose = true,
   enableContentPanningGesture = true,
   enableDynamicSizing = true,
+  disableAutomaticBottomPadding = false,
```
Comment (CassioMG) [inline src/components/BottomSheet.tsx:68]: would you mind updating it to `useInsetsBottomPadding = true` ? I think it will sound more consistent with what we currently have on `BaseLayout`. Then setting it to `false` on the swap screen - thanks!

Comment (danilosilvackl) [reply src/components/BottomSheet.tsx]: done!
